# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/dzy/deep2/pytorch/yolov11/pig_modify/yolov11-main/ui/alertdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(976, 621)
        Dialog.setStyleSheet("background-color: rgb(88, 155, 255);")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setStyleSheet("font: 75 24pt \"Arial\";\n"
"background-color: rgb(7,87,169);\n"
"border-radius: 6px;\n"
"border: 1px solid #0B5BB2;\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setStyleSheet("font: 75 13pt \"Arial\";\n"
"color: rgb(255,255,255); ")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableView = QtWidgets.QTableView(self.groupBox_2)
        self.tableView.setStyleSheet("background-color: rgb(88, 155, 255);")
        self.tableView.setObjectName("tableView")
        self.gridLayout_2.addWidget(self.tableView, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setStyleSheet("background-color: rgb(7, 87, 169); \n"
"font: 75 16pt \"Arial\";\n"
"color: rgb(255,255,255); ")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.comboBox_video = QtWidgets.QComboBox(Dialog)
        self.comboBox_video.setMinimumSize(QtCore.QSize(300, 30))
        self.comboBox_video.setMaximumSize(QtCore.QSize(300, 30))
        self.comboBox_video.setStyleSheet("background-color: rgb(7, 87, 169); \n"
"font: 75 16pt \"Arial\";\n"
"color: rgb(255,255,255); ")
        self.comboBox_video.setObjectName("comboBox_video")
        self.horizontalLayout.addWidget(self.comboBox_video)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setStyleSheet("background-color: rgb(7, 87, 169); \n"
"font: 75 16pt \"Arial\";\n"
"color: rgb(255,255,255); ")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox_id = QtWidgets.QComboBox(Dialog)
        self.comboBox_id.setMinimumSize(QtCore.QSize(100, 30))
        self.comboBox_id.setMaximumSize(QtCore.QSize(100, 30))
        self.comboBox_id.setStyleSheet("background-color: rgb(7, 87, 169); \n"
"font: 75 16pt \"Arial\";\n"
"color: rgb(255,255,255); ")
        self.comboBox_id.setObjectName("comboBox_id")
        self.horizontalLayout.addWidget(self.comboBox_id)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "pig运动分析系统"))
        self.groupBox_2.setTitle(_translate("Dialog", "详情"))
        self.label_3.setText(_translate("Dialog", "视频ID:"))
        self.label_2.setText(_translate("Dialog", "目标ID选择："))
